### ISSUE TITLE
siomiz/SoftEtherVPN:latest docker container terminates intermittently with exit code 137

### ISSUE THREAD

**Issue by linbrown** [siomiz/SoftEtherVPN#2] opened 2016-01-12 00:48 UTC
Here is the additional information:

1. The host machine is running CentOS Linux release 7.1.1503 (Core)

2. The docker version 1.9.1, build a34a1d5

3. The docker command to start the container:

docker run -d -p 500:500/udp -p 4500:4500/udp -p 1701:1701/tcp --name CONTANER_NAME -e PSK=ACTUAL_PHRASE -e USERNAME=ACTUAL_NAME -e PASSWORD=ACTUAL_PASSWORD siomiz/softethervpn:latest

When using "--cap-add NET_ADMIN", the behavior did not seem to change. But if using "--privileged" flag, the VPN runs for much longer time before terminates.

Thanks a lot

**Comment by linbrown** [comment] 2016-01-12 00:51
P.S.

I did not use any client software. I ran on iPhone the interface to add VPN. On Windows, I used  "Set up a new connection on network" interface in "Network and Sharing Center".

**Comment by siomiz** [comment] 2016-01-12 01:37
Could you try the `docker-engine` with SELinux policy bundled
from http://yum.dockerproject.org/repo/testing/centos/7/Packages/ ?

ref. docker/docker#15832

**Comment by siomiz** [comment] 2016-01-12 19:59
hmm.

for me (on CoreOS 835.9.0, Docker 1.8.3), this event:
```
systemd-journal[23295]: Permanent journal (/var/log/journal/) is currently using 4.0G.
                        Maximum allowed usage is set to 4.0G.
                        Leaving at least 4.0G free (of currently available 16.5G of space).
                        Enforced usage limit is thus 4.0G.
systemd-journal[23295]: Journal started
systemd-coredump[23291]: Detected coredump of the journal daemon itself, diverted to /var/lib/systemd/coredump/core.systemd-journal.0.5c7ef4...
```
somehow automatically killed/restarted the `dockerd` service, then immediately after, this `systemd` error:
```
systemd[1]: systemd-journald.service: Watchdog timeout (limit 1min)!
...
systemd[1]: libcontainer-23328-systemd-test-default-dependencies.scope: Scope has no PIDs. Refusing.
```
probably killed containers resulting in exit code 137, including the one running softethervpn.

ref. coreos/bugs#351 (I'm sure CentOS has a similar issue filed)

As a workaround, if you are managing the softethervpn container as a systemd service, adding `Restart=always` to `[Service]` section might help keeping it alive until the issue is fixed upstream.

**Comment by linbrown** [comment] 2016-01-13 23:48
I added "Restart=always" to [Service] section in /usr/lib/systemd/system/docker.service and restarted docker daemon. Started the docker container without "--privileged" flag. Unfortunately the container still terminated. I just started the container with "--privileged" flag.

Just realize that you want me to run the container as a service. I have to figure out how to do that.

Regarding using docker-engine with SeLinux policy bundled, I am not in the position to try that now. I will do it in about a month.

**Comment by linbrown** [comment] 2016-01-14 02:21
I started the container with "--restart=always" flag (https://docs.docker.com/engine/reference/commandline/run/). I believe that this is what you want me to do. If this works, I can decide if other choices for "--restart" flag may be a better option. 

Thanks for your help! I will get you know what happens.

**Comment by siomiz** [comment] 2016-01-14 05:28
Thank you for the update!
No need to run the container as a service; as long as the restart flag is set for the container (assuming docker daemon is kept alive).

The more I look into this, the more I'm inclined to believe that something external (systemd watchdog?) is SIGKILL'ing our container... ref. coreos/bugs#1001

I'll continue investigating to see if this image actually requires more than NET_ADMIN cap.

**Comment by linbrown** [comment] 2016-01-15 10:49
I have been running the VPN container with "--restart=always" for over a day. Restarting the container worked. For some reasons, connecting to the VPN server seems to be faster than without the flag.

Here is the command I used:

docker run -d --restart=always -p 500:500/udp -p 4500:4500/udp -p 1701:1701/tcp --name CONTANER_NAME -e PSK=ACTUAL_PHRASE -e USERNAME=ACTUAL_NAME -e PASSWORD=ACTUAL_PASSWORD siomiz/softethervpn:latest

I prefer to run with the least privileges possible. I would be interested to know if NET_ADMIN capability is really necessary too and how it works.

Thank you for your help!

**Comment by siomiz** [comment] 2016-01-16 01:40
Glad it's been stable for now...
siomiz/SoftEtherVpn#3 might've helped reduce lag a bit.

[SoftEtherVPN server uses `iptables` internally, for example](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/4e862a7e40c095ac6ac8b1417890008fbd614ebb/src/Cedar/NativeStack.c#L669),
and running `iptables` within Docker containers requires the `NET_ADMIN` cap.

You can see the difference:
```
~$ docker run --rm alpine sh -c "apk -q update && apk -q add iptables && iptables -L"
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```
```
~$ docker run --rm --cap-add=NET_ADMIN alpine sh -c "apk -q update && apk -q add iptables && iptables -L"
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

**Comment by linbrown** [comment] 2016-01-22 02:11
I understand that you proposed a new version which may work better. Thank you very much! Unfortunately I am not in the position to make the update. 

So given the configuration I had 7 days ago (starting the container with "--restart=always"), I ran into an interesting situation. If the running container terminates with exit code "-1", the container will never be able to restart again by Docker daemon. I had to restart it manually. I had 2 instances already. I am just curious if you know what is going on.

Thanks again!

**Comment by siomiz** [comment] 2016-01-25 22:56
Since you are already on Docker 1.9+, you can try the new `--restart=unless-stopped` option instead.

If the problem persists, you should file an issue at https://github.com/docker/docker/issues ...

**Comment by bprodoehl** [comment] 2016-01-26 20:11
I think this container is missing the iptables package.  Upon running what's in the Docker Hub, I received messages about iptables not being found.  I exec'd in, and sure enough, yum install iptables wants to install iptables.  I only mention it in this ticket because @siomiz points out above that iptables is used internally.

**Comment by siomiz** [comment] 2016-01-27 00:16
Ooh you're right, I forgot I was running **:openvpn** as my service.

```
$ docker run --rm siomiz/softethervpn:latest /sbin/iptables --version
...
/entrypoint.sh: line 71: /sbin/iptables: No such file or directory
```
```
$ docker run --rm siomiz/softethervpn:openvpn /sbin/iptables --version
...
iptables v1.4.21
```
They must've removed `iptables` from `centos:centos7` at some point...
I'll merge openvpn to reduce confusions.
Thank you @bprodoehl!

**Comment by siomiz** [comment] 2016-01-27 01:52
Ok, it's still building on Docker Hub but `iptables` is installed on the **:latest** image.
Hope this reduced the number of error exit scenarios.

**Comment by siomiz** [comment] 2016-07-18 21:55
I would like to believe this is fixed in upstream. 
Please reopen if it still happens...

**Closed by siomiz** 2016-07-18 21:55 UTC
